---
- name: Install and start Nginx on Ubuntu
  hosts: all
  gather_facts: no

 tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present
