---
- name: Install nginx on Ubuntu
  hosts: webservers
  become: yes
  gather_facts: no

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present
